FROM agoldis/sorry-cypress-director

ENV DASHBOARD_URL=https://cypress-dashboard-gp34ticnkq-ey.a.run.app
ENV EXECUTION_DRIVER=../execution/mongo/driver
ENV SCREENSHOTS_DRIVER=../screenshots/minio.driver
ENV MONGODB_DATABASE=cypress
ENV MINIO_ENDPOINT=cypress-minio-gp34ticnkq-ey.a.run.app
ENV MINIO_URL=https://cypress-minio-gp34ticnkq-ey.a.run.app
ENV MINIO_PORT=443
ENV MINIO_USESSL=true
ENV MINIO_BUCKET=sorrycypress